status = [
  "build (macos-10.15, true)",
  "build (macos-10.15, false)",
  "build (ubuntu-18.04, true)",
  "build (ubuntu-18.04, false)",
  "build (windows-2019, true)",
  "build (windows-2019, false)",
  "docs",
]

timeout_sec = 18000 # 5 hours
