[package]
name = "wgpu"
version = "0.4.0"
authors = [
    "Dzmitry Malyshau <kvark@mozilla.com>",
    "Joshua Groves <josh@joshgroves.com>",
    "Lucas Kent <rubickent@gmail.com>",
    "kyren <kerriganw@gmail.com>",
    "Cormac O'Brien <cormac@c-obrien.org>",
]
edition = "2018"
description = "Rusty WebGPU API wrapper"
homepage = "https://github.com/gfx-rs/wgpu-rs"
repository = "https://github.com/gfx-rs/wgpu-rs"
keywords = ["graphics"]
license = "MPL-2.0"
exclude = ["etc/**/*", "examples/**/*", "tests/**/*", "Cargo.lock", "target/**/*"]

[lib]

[features]
default = []
# Make Vulkan backend available on platforms where it is by default not, e.g. macOS
vulkan = ["wgn/vulkan-portability"]

[dependencies.wgn]
package = "wgpu-native"
version = "0.4"
git = "https://github.com/gfx-rs/wgpu"
rev = "08e8d406c175579da5ef18c1abf4d6c00e2a9726"

[dependencies.wgc]
package = "wgpu-core"
version = "0.1"
git = "https://github.com/gfx-rs/wgpu"
rev = "08e8d406c175579da5ef18c1abf4d6c00e2a9726"

[dependencies.wgt]
package = "wgpu-types"
version = "0.1"
git = "https://github.com/gfx-rs/wgpu"
rev = "08e8d406c175579da5ef18c1abf4d6c00e2a9726"

[dependencies]
arrayvec = "0.5"
smallvec = "1"
raw-window-handle = "0.3"
parking_lot = "0.10"

[dev-dependencies]
cgmath = "0.17"
env_logger = "0.7"
glsl-to-spirv = "0.1"
log = "0.4"
png = "0.15"
winit = "0.22"
rand = "0.7.2"
zerocopy = "0.3"
futures = "0.3"

#[patch."https://github.com/gfx-rs/wgpu"]
#wgc = { version = "0.1.0", package = "wgpu-core", path = "../wgpu/wgpu-core" }
#wgt = { version = "0.1.0", package = "wgpu-types", path = "../wgpu/wgpu-types" }
#wgn = { version = "0.4.0", package = "wgpu-native", path = "../wgpu/wgpu-native" }

[[example]]
name="hello-compute"
path="examples/hello-compute/main.rs"
test = true
