[package]
name = "wgpu"
version = "0.4.0"
authors = [
    "Dzmitry Malyshau <kvark@mozilla.com>",
    "Joshua Groves <josh@joshgroves.com>",
    "Lucas Kent <rubickent@gmail.com>",
    "kyren <kerriganw@gmail.com>",
    "Cormac O'Brien <cormac@c-obrien.org>",
]
edition = "2018"
description = "Rusty WebGPU API wrapper"
homepage = "https://github.com/gfx-rs/wgpu-rs"
repository = "https://github.com/gfx-rs/wgpu-rs"
keywords = ["graphics"]
license = "MPL-2.0"
exclude = ["etc/**/*", "examples/**/*", "tests/**/*", "Cargo.lock", "target/**/*"]

[lib]

[features]
default = []
# Make Vulkan backend available on platforms where it is by default not, e.g. macOS
vulkan = ["wgn/vulkan-portability"]

[dependencies.wgn]
package = "wgpu-native"
version = "0.4"
git = "https://github.com/gfx-rs/wgpu"
rev = "c293d6dcea0170bfa3835cfbd919f300560e0da6"
#path = "../wgpu/wgpu-native"

[dependencies.wgc]
package = "wgpu-core"
version = "0.1"
git = "https://github.com/gfx-rs/wgpu"
rev = "c293d6dcea0170bfa3835cfbd919f300560e0da6"
#path = "../wgpu/wgpu-core"

[dependencies]
arrayvec = "0.5"
smallvec = "1"
raw-window-handle = "0.3"

[dev-dependencies]
cgmath = "0.17"
env_logger = "0.7"
glsl-to-spirv = "0.1"
log = "0.4"
png = "0.15"
winit = "0.20.0"
rand = "0.7.2"
zerocopy = "0.2"
futures = "0.3"
