[package]
name = "wgpu"
version = "0.5.0"
authors = [
    "Dzmitry Malyshau <kvark@mozilla.com>",
    "Joshua Groves <josh@joshgroves.com>",
    "Lucas Kent <rubickent@gmail.com>",
    "kyren <kerriganw@gmail.com>",
    "Cormac O'Brien <cormac@c-obrien.org>",
]
edition = "2018"
description = "Rusty WebGPU API wrapper"
homepage = "https://github.com/gfx-rs/wgpu-rs"
repository = "https://github.com/gfx-rs/wgpu-rs"
keywords = ["graphics"]
license = "MPL-2.0"
exclude = ["etc/**/*", "examples/**/*", "tests/**/*", "Cargo.lock", "target/**/*"]

[lib]

[features]
default = []
# Make Vulkan backend available on platforms where it is by default not, e.g. macOS
vulkan = ["wgn/vulkan-portability"]

[dependencies.wgn]
package = "wgpu-native"
version = "0.5"
#git = "https://github.com/gfx-rs/wgpu"

[dependencies.wgc]
package = "wgpu-core"
version = "0.5"
#git = "https://github.com/gfx-rs/wgpu"

[dependencies.wgt]
package = "wgpu-types"
version = "0.5"
#git = "https://github.com/gfx-rs/wgpu"

[dependencies]
arrayvec = "0.5"
smallvec = "1"
raw-window-handle = "0.3"
parking_lot = "0.10"

[dev-dependencies]
cgmath = "0.17"
env_logger = "0.7"
glsl-to-spirv = "0.1"
log = "0.4"
png = "0.15"
winit = "0.22"
rand = "0.7.2"
zerocopy = "0.3"
futures = "0.3"

[[example]]
name="hello-compute"
path="examples/hello-compute/main.rs"
test = true

#[patch.crates-io]
#wgpu-types = { version = "0.5.0", path = "../wgpu/wgpu-types" }
#wgpu-core = { version = "0.5.0", path = "../wgpu/wgpu-core" }
#wgpu-native = { version = "0.5.0", path = "../wgpu/wgpu-native" }

#[patch.crates-io]
#gfx-hal = { version = "0.5.0", path = "../gfx/src/hal" }
#gfx-backend-empty = { version = "0.5.0", path = "../gfx/src/backend/empty" }
#gfx-backend-vulkan = { version = "0.5.0", path = "../gfx/src/backend/vulkan" }
#gfx-backend-dx12 = { version = "0.5.0", path = "../gfx/src/backend/dx12" }
#gfx-backend-dx11 = { version = "0.5.0", path = "../gfx/src/backend/dx11" }
#gfx-descriptor = { version = "0.1.0", path = "../gfx-extras/gfx-descriptor" }
#gfx-memory = { version = "0.1.0", path = "../gfx-extras/gfx-memory" }
