name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
        continue-on-error: true

      - name: Build the docs (nightly)
        run: |
          cargo +nightly doc --lib --all-features

      - name: Build the docs (stable)
        run: cargo +stable doc --lib --all-features
        if: ${{ failure() }}

      - name: Deploy the docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: target/doc
          REPOSITORY_NAME: gfx-rs/wgpu-rs.github.io
          BRANCH: master
          TARGET_FOLDER: doc 
